apiVersion: v1
kind: Secret
metadata:
  name: trainer-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
type: Opaque
data:
  name:
  project: ZGVmYXVsdA==
  url:
